{{- if (eq .Values.ingress.class "traefik") }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: websocket-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customFrameOptionsValue: "SAMEORIGIN"
    referrerPolicy: "no-referrer"
    customRequestHeaders:
      # Required for WebSocket handshake
      Connection: "Upgrade"
      Upgrade: "websocket"
    customResponseHeaders:
      X-WebSocket-Enabled: "true"
{{- end }}
